
name: CI-CD-Pipeline-to-aws
env:
  EB_PACKAGE_S3_BUCKET_NAME: "my-first-bucket-app"
  EB_APPLICATION_NAME: "My-APP"
  EB_EMVOIRMENT_NAME: "My-APP-env"
  DEPLOY_PACKAGE_NAME: "flask-app${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east"



on:
  push:
    branches: [ master ]

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps:
    - name: git clone our repo
      uses: actions/checkout@v2

    - name: Create ZIP Deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    - name: configure my aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_acces_key_id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws_secret_key_id: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws_region: ${{ env.AWS_REGION_NAME }}
        
    - name: Copy deployment package to s3-bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}
      
    - name: print happy message
      run: echo "ci pipeline part finish successfully"
